name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  mobx: ^2.6.0
  flutter_mobx: ^2.3.0
  provider: ^6.1.5

  # Network
  dio: ^5.9.2
  cached_network_image: ^3.4.1 

  # UI
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0  

  # Storage and 
  shared_preferences: ^2.5.5 

  # DI
  get_it: ^9.2.1
  injectable: ^2.7.1

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

  # Codegen
  build_runner: ^2.13.1
  flutter_gen_runner: ^5.13.0
  mobx_codegen: ^2.7.6
  injectable_generator: ^2.12.1
  freezed: ^3.0.0
  json_serializable: ^6.9.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png"

flutter_gen:
  output: lib/src/core/icons/gen/

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/info.webp
    - assets/icons/character_species/alien.webp
    - assets/icons/character_species/human.webp
    - assets/icons/character_gender/female.webp
    - assets/icons/character_gender/male.webp
    - assets/icons/character_gender/unknown.webp
    - assets/icons/character_status/alive.webp
    - assets/icons/character_status/dead.webp
    - assets/icons/character_status/unknown.webp

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
