name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

fonts:
  - family: Aeonik
    fonts:
      - asset: assets/fonts/lato/Lato-Regular.ttf
      - asset: assets/fonts/lato/Lato-Bold.ttf
        weight: 700
      - asset: assets/fonts/lato/Lato-Italic.ttf
        style: italic
      - asset: assets/fonts/lato/Lato-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/lato/Lato-Black.ttf
        weight: 900
      - asset: assets/fonts/lato/Lato-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: assets/fonts/lato/Lato-Light.ttf
        weight: 300
      - asset: assets/fonts/lato/Lato-LightItalic.ttf
        weight: 300
        style: italic
      - asset: assets/fonts/lato/Lato-Thin.ttf
        weight: 100
      - asset: assets/fonts/lato/Lato-ThinItalic.ttf
        weight: 100
        style: italic
