name: rick_and_morty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  cached_network_image: ^3.4.1
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  dio: ^5.7.0
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  mobx_codegen: ^2.6.2
  injectable_generator: ^2.6.2

flutter_gen:
  output: lib/src/core/icons/gen/

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/localization/l10n
  output_dir: lib/src/core/localization/generated

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/info.webp
    - assets/icons/character_species/alien.webp
    - assets/icons/character_species/human.webp
    - assets/icons/character_gender/female.webp
    - assets/icons/character_gender/male.webp
    - assets/icons/character_gender/unknown.webp
    - assets/icons/character_status/alive.webp
    - assets/icons/character_status/dead.webp
    - assets/icons/character_status/unknown.webp

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
